name: "veigo assistant"

services:
  server:
    container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_CONTAINER_PORT}"
    env_file:
      - .env
    volumes:
      - ${SERVER_VOLUME}:/app/source