name: "veigo-assistant"

services:
  bot:
    build:
      context: ${BOT_CONTEXT_PATH}
    container_name: ${BOT_CONTAINER_NAME}
    ports:
      - "${BOT_HOST_PORT}:${BOT_CONTAINER_PORT}"
    environment:
      IS_DEVELOPMENT: true
      PORT: ${BOT_CONTAINER_PORT}
      DATABASE_CONNECTION: postgres://${DB_USER}:${DB_PASSWORD}@${DB_CONTAINER_NAME}:${DB_CONTAINER_PORT}
      DATABASE_DEFAULT_NAME: ${DB_DEFAULT_NAME}
      DATABASE_NAME: ${DB_NAME}
      AI_CONNECTION: http://${AI_CONTAINER_NAME}:${AI_CONTAINER_PORT}
      AUTHOR_PROFILE_URL: ${AUTHOR_PROFILE_URL}
      AUTHOR_IMAGE_URL: ${AUTHOR_IMAGE_URL}
      AUTHOR_NAME: ${AUTHOR_NAME}
      AUTHOR_NICKNAME: ${AUTHOR_NICKNAME}
      AUTHOR_SIGNATURE: ${AUTHOR_SIGNATURE}
    env_file:
      - ${BOT_CONTEXT_PATH}/${BOT_ENV_FILE}
    depends_on:
      - ai
      - db
    volumes:
      - ${BOT_CONTEXT_PATH}/${BOT_VOLUME}:/app/source

  ai:
    build:
      context: ${AI_CONTEXT_PATH}
      args:
        MODEL_URL: ${MODEL_URL}
        MODEL_PATH: ${MODEL_PATH}
        MODEL_NAME: ${MODEL_NAME}
    container_name: ${AI_CONTAINER_NAME}
    ports:
      - "${AI_HOST_PORT}:${AI_CONTAINER_PORT}"
    environment:
      SERVER_PORT: ${AI_CONTAINER_PORT}
      MODEL_URL: ${MODEL_URL}
      MODEL_PATH: ${MODEL_PATH}
      MODEL_NAME: ${MODEL_NAME}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - ${AI_CONTEXT_PATH}/${AI_VOLUME}:/app

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:latest
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DEFAULT_NAME}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data